Version 4
SymbolType CELL
LINE Normal -29 16 -16 32
LINE Normal -3 16 -29 16
LINE Normal -16 32 -3 16
LINE Normal -3 32 -29 32
LINE Normal -16 16 -16 -16
LINE Normal -48 -16 -16 -16
LINE Normal -16 64 -16 32
LINE Normal -48 64 -16 64
LINE Normal 70 -16 70 16
LINE Normal 112 -16 70 -16
LINE Normal 70 64 70 32
LINE Normal 112 64 70 64
LINE Normal 74 16 83 32
LINE Normal 91 16 74 16
LINE Normal 83 32 91 16
LINE Normal 94 32 66 32
LINE Normal 66 32 57 16
LINE Normal 48 32 66 32
LINE Normal 57 16 48 32
LINE Normal 45 16 74 16
LINE Normal 30 16 12 16
LINE Normal 24 12 30 16
LINE Normal 25 20 30 16
LINE Normal 30 32 12 32
LINE Normal 24 28 30 32
LINE Normal 25 36 30 32
LINE Normal 94 16 91 16
LINE Normal 45 32 48 32
LINE Normal 38 -16 70 -16 2
LINE Normal 38 44 38 -16 2
LINE Normal 54 64 70 64 2
RECTANGLE Normal 112 96 -48 -48
RECTANGLE Normal 54 83 10 44
TEXT -43 -32 Left 0 led+
TEXT -43 80 Left 0 led-
TEXT 62 -31 Left 0 mt2
TEXT 62 79 Left 0 mt1
TEXT 13 62 Left 0 zcd
WINDOW 38 32 112 Center 0
WINDOW 0 32 -64 Center 0
SYMATTR SpiceModel LED_TRIAC_ZCS
SYMATTR Prefix X
SYMATTR Description OPTO-TRIAC with zero crossing switching
PIN -48 -16 NONE 8
PINATTR PinName led+
PINATTR SpiceOrder 1
PIN -48 64 NONE 8
PINATTR PinName led-
PINATTR SpiceOrder 2
PIN 112 -16 NONE 8
PINATTR PinName mt2
PINATTR SpiceOrder 3
PIN 112 64 NONE 8
PINATTR PinName mt1
PINATTR SpiceOrder 4
